### ISSUE TITLE
Add options for subscribers to rate limit calling their callback

### ISSUE THREAD

**Issue by curtismuntz** [agtonomy/trellis#27]
**Is your feature request related to a problem? Please describe.**
I have a plotting utility that I'm using that is having trouble keeping up with subscription messages coming from a high rate publisher. Other nodes on my network benefit immensely from the high update rate of the publisher. Is there a way to add some optional message dropping mechanisms to the subscriber class?

**Describe the solution you'd like**
It'd be nice to have the ability to drop every n messages, or perhaps lock a subscriber to a maximum update rate. Maybe something like a template argument?
```
const int drop_every_n_msgs = 1;
trellis::core::MessageConsumer<1, drop_every_n_msgs, HighRateProto> high_rate_subscriber_
```
or:
```
const int max_update_rate_ms = 20;
trellis::core::MessageConsumer<1, max_update_rate_ms, HighRateProto> high_rate_subscriber_
```

**Describe alternatives you've considered**
Right now I'm rate limiting the subscriber by managing a skip flag, but this is clunky and doesn't scale well in the event I want to rate limit several topics, especially when using the `CreateDynamicSubscriber()` mechanism.

I could also reduce the publisher's rate, but thats not desireable because other nodes on my network can keep up with the data rate.

**Additional context**
I also would heavily enjoy this feature in the `CreateDynamicSubscriber` method, as this is my primary use case for rate limiting subscription topics for plotting.

**Comment by bsirang** [comment]
This feature makes sense to me. I'm leaning towards allowing a "maximum frequency" parameter for `trellis::core::Subscriber` instances. Also currently `trellis::core::DynamicSubscriber` is an alias to eCAL's dynamic subscriber. So it will need to be wrapped to support this feature, which is very doable.

After `trellis::core::Subscriber` supports the feature then `trellis::core::MessageConsumer` API can be updated to support it as well.

**Comment by pickledgator** [comment]
This is going to be useful for the gRPC bridge too since we won't want to push full bandwidth trellis streams out to the external APIs.

**Comment by bsirang** [comment]
PR https://github.com/agtonomy/trellis/pull/30 removes the direct alias from `trellis::core::DynamicSubscriber` to eCAL and instead reuses `trellis::core::SubscriberImpl`. Next step is to extend `trellis::core::SubscriberImpl` to support rate throttling.

**Comment by bsirang** [comment]
PR https://github.com/agtonomy/trellis/pull/32 adds the max frequency option to subscribers. Next step is to add an API to `MessageConsumer`

**Comment by bsirang** [comment]
PR https://github.com/agtonomy/trellis/pull/34 extends `MessageConsumer` to support the subscriber frequency throttle. Closing.
