### ISSUE TITLE
[QST] Is there any development model or contribution guide?

### ISSUE THREAD

**Issue by ZhenshengLee** [agtonomy/trellis#84]
First of all, nice to see this opensource repo as the middleware for agricultural autonomous system.

But what is the development model currently? The Cathedral model or The Bazaar model?

And what can I do if I want to pay some attention to the project?

Thanks!

**Comment by bsirang** [comment]
Hello,

Thank you for your interest in contribution. We follow the Bazaar model as best I can tell (I had to look up the terminology). We issue PR's publicly in this repository. We do not yet have a release process as this project is still in its infancy.

Here is a README about contributing. It mentions code contributions at the bottom: https://github.com/agtonomy/trellis/blob/master/CONTRIBUTING.md

Simply following this repository on Github is the best way to stay up to date.

**Comment by ZhenshengLee** [comment]
Thanks and closing this.
